language: objective-c
xcode_project: Socket.IO-Client-Swift.xcodeproj # path to your xcodeproj folder
xcode_scheme: SocketIO-Mac
osx_image: xcode7
before_install:
    - brew update
    - brew outdated xctool || brew upgrade xctool
script: xcodebuild -project Socket.IO-Client-Swift.xcodeproj -scheme SocketIO-Mac clean test
